name: Unica Kernel Build

on:
  workflow_dispatch:
    inputs:
      device:
        description: "Target device codename (x1q , y2q , z3q , c1q , c2q , r8q)"
        required: true
        default: "y2q"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7
        with:
          submodules: recursive   # fetch submodules

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            unzip \
            wget \
            zip \
            zstd \
            bc \
            bison \
            flex \
            libssl-dev \
            rsync \
            ccache \
            python3 \
            llvm \
            lld

      - name: Cache Clang toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: clang-r547379
          key: clang-r547379-cache

      - name: Download prebuilt Google clang (if not cached)
        if: steps.cache-clang.outputs.cache-hit != 'true'
        run: |
          wget --no-cookies --header "Cookie: gi=0" -O clang-r547379.tar.gz \
            https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-r547379.tar.gz
          mkdir -p clang-r547379
          cd clang-r547379
          tar -xf ../clang-r547379.tar.gz
          cd ..
          rm clang-r547379.tar.gz

      - name: Run kernel build
        run: |
          chmod +x build_sm8250.sh
          ./build_sm8250.sh ${{ github.event.inputs.device }}

      - name: Upload kernel zip
        uses: actions/upload-artifact@v5
        with:
          name: unica-kernel-${{ github.event.inputs.device }}
          path: |
            *.zip
